// <auto-generated />
namespace eStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class _00_Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_00_Initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201310040113241_00_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
