// <auto-generated />
namespace eStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _02_BlogForum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02_BlogForum));
        
        string IMigrationMetadata.Id
        {
            get { return "201310202330310_02_BlogForum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
