// <auto-generated />
namespace eStore.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _01_SimpleMembership : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01_SimpleMembership));
        
        string IMigrationMetadata.Id
        {
            get { return "201310010851132_01_SimpleMembership"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
