// <auto-generated />
namespace eStore.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _00_Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_00_Initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201310010849145_00_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
